package database

import (
	"context"
	"os"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/Silo-Server/silo-server/migrations"
)

// TestMigrateDownToRefusesOutOfRangeCoreIDs is the rollback rehearsal for the
// bigint widening (20260901204344). Its Down narrows users.id,
// media_files.id and media_folders.id back to integer and must refuse, before
// any ALTER runs, when a stored id no longer fits. The text contract test in
// migrations/ pins the guard's shape; this proves the plpgsql actually runs
// through MigrateDownTo, names the offending table, and leaves the columns
// bigint on refusal.
func TestMigrateDownToRefusesOutOfRangeCoreIDs(t *testing.T) {
	dsn := os.Getenv("SILO_TEST_DATABASE_URL")
	if dsn == "" {
		t.Skip("SILO_TEST_DATABASE_URL is not set")
	}
	ctx := context.Background()
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Fatalf("connect: %v", err)
	}
	// Registered before the re-up cleanup so it runs after it (cleanups are LIFO).
	t.Cleanup(pool.Close)

	if err := RunMigrations(ctx, pool, migrations.FS, "sql"); err != nil {
		t.Fatalf("migrate up: %v", err)
	}
	// Leave the database at head whatever happens below.
	t.Cleanup(func() {
		_, _ = pool.Exec(ctx, `DELETE FROM media_folders WHERE id > 2147483647 OR id < -2147483648`)
		if err := RunMigrations(ctx, pool, migrations.FS, "sql"); err != nil {
			t.Errorf("re-up after test: %v", err)
		}
	})

	const beforeWidening = 20260901180726
	columnType := func(table string) string {
		t.Helper()
		var typ string
		if err := pool.QueryRow(ctx, `SELECT data_type FROM information_schema.columns
			 WHERE table_schema='public' AND table_name=$1 AND column_name='id'`, table).Scan(&typ); err != nil {
			t.Fatalf("column type of %s.id: %v", table, err)
		}
		return typ
	}
	parents := []string{"media_folders", "users", "media_files"}
	for _, table := range parents {
		if got := columnType(table); got != "bigint" {
			t.Fatalf("%s.id is %q at head, want bigint", table, got)
		}
	}

	// The identity column is GENERATED BY DEFAULT, so an explicit id is
	// accepted without OVERRIDING SYSTEM VALUE. One case per end of the int4
	// range: the Down must name the table and the value either way.
	for _, tc := range []struct {
		name string
		id   int64
	}{
		{"above int4", 3_000_000_000},
		{"below int4", -3_000_000_000},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := pool.Exec(ctx,
				`INSERT INTO media_folders (id, type, name) VALUES ($1, 'movies', 'downguard')`,
				tc.id); err != nil {
				t.Fatalf("seed out-of-range folder: %v", err)
			}
			defer func() {
				if _, err := pool.Exec(ctx, `DELETE FROM media_folders WHERE id=$1`, tc.id); err != nil {
					t.Fatalf("delete seeded folder: %v", err)
				}
			}()

			err := MigrateDownTo(ctx, pool, migrations.FS, "sql", beforeWidening)
			if err == nil {
				t.Fatal("MigrateDownTo succeeded with an out-of-range media_folders.id; the guard did not run")
			}
			if !strings.Contains(err.Error(), "widen_core_ids_to_bigint down: public.media_folders.id holds") {
				t.Fatalf("MigrateDownTo error does not name the table and value: %v", err)
			}
			for _, table := range parents {
				if got := columnType(table); got != "bigint" {
					t.Errorf("%s.id is %q after the refused down, want bigint (the guard ran too late)", table, got)
				}
			}
		})
	}

	// With the rows gone the Down narrows all three, and the Up restores them.
	if err := MigrateDownTo(ctx, pool, migrations.FS, "sql", beforeWidening); err != nil {
		t.Fatalf("MigrateDownTo after removing the row: %v", err)
	}
	for _, table := range parents {
		if got := columnType(table); got != "integer" {
			t.Errorf("%s.id is %q after down, want integer", table, got)
		}
	}
	if err := RunMigrations(ctx, pool, migrations.FS, "sql"); err != nil {
		t.Fatalf("re-up: %v", err)
	}
	for _, table := range parents {
		if got := columnType(table); got != "bigint" {
			t.Errorf("%s.id is %q after re-up, want bigint", table, got)
		}
	}
}
