package migrations

import (
	"fmt"
	"strings"
	"testing"
)

// The three standardization migrations carry decisions that are easy to undo by
// accident: which tables convert to identity and that the conversion is BY
// DEFAULT (serial parity) rather than ALWAYS; that the identity sequence is
// positioned from the old sequence so ids keep counting instead of restarting
// at 1; the exact varchar columns that become text and the lengths the Down
// restores; and the three rename pairs with every index and constraint that
// follows them. These tests pin all of that as text.

const (
	serialToIdentityMigration = "sql/20260901180714_serial_ids_to_identity.sql"
	varcharToTextMigration    = "sql/20260901180715_notification_varchar_to_text.sql"
	renameTablesMigration     = "sql/20260901180726_rename_tables_for_consistency.sql"
)

// serialToIdentityTables is the audit result: every public table whose id
// column had a nextval() default on an owned sequence after the full chain,
// excluding activity_log's partitions (which inherit the parent's conversion).
var serialToIdentityTables = []string{
	"abs_sessions",
	"activity_log",
	"api_keys",
	"artwork_revision_gc_candidates",
	"autoscan_events",
	"autoscan_webhook_deliveries",
	"catalog_search_index_events",
	"download_artifact_orphans",
	"downloaded_subtitles",
	"invite_codes",
	"marker_edit_audit",
	"media_files",
	"media_folder_paths",
	"media_folders",
	"media_identity_overrides",
	"metadata_image_cache_jobs",
	"metadata_translation_jobs",
	"playback_route_events",
	"plugin_auth_bindings",
	"plugin_auth_identities",
	"plugin_capabilities",
	"plugin_installations",
	"plugin_repositories",
	"plugin_runtime_configs",
	"plugin_task_bindings",
	"stream_nodes",
	"subtitle_ai_jobs",
	"task_executions",
	"task_triggers",
	"user_setting_migration_rejects",
	"user_setting_values",
	"users",
}

// targetsArray extracts the quoted names inside the first ARRAY[...] literal
// after marker in s.
func targetsArray(t *testing.T, s, marker string) []string {
	t.Helper()
	_, rest, ok := strings.Cut(s, marker)
	if !ok {
		t.Fatalf("missing %q", marker)
	}
	_, rest, ok = strings.Cut(rest, "ARRAY[")
	if !ok {
		t.Fatal("missing targets ARRAY[")
	}
	body, _, ok := strings.Cut(rest, "]")
	if !ok {
		t.Fatal("targets array unterminated")
	}
	var names []string
	for _, part := range strings.Split(body, ",") {
		names = append(names, strings.Trim(strings.TrimSpace(part), "'"))
	}
	return names
}

func TestSerialToIdentityMigrationContract(t *testing.T) {
	up, down := readMigrationSections(t, serialToIdentityMigration)

	for _, section := range []struct {
		name string
		body string
	}{{"up", up}, {"down", down}} {
		got := targetsArray(t, section.body, "targets text[]")
		if len(got) != len(serialToIdentityTables) {
			t.Fatalf("%s converts %d tables, contract lists %d: update this test alongside the migration",
				section.name, len(got), len(serialToIdentityTables))
		}
		for i, want := range serialToIdentityTables {
			if got[i] != want {
				t.Errorf("%s targets[%d] = %q, want %q (list is sorted and pinned)", section.name, i, got[i], want)
			}
		}
	}

	// BY DEFAULT is serial parity: an INSERT may still supply the id. ALWAYS
	// would reject internal/api/handlers/policy_test.go's explicit-id insert
	// and any restore path that carries ids across databases.
	if !strings.Contains(up, "ADD GENERATED BY DEFAULT AS IDENTITY") {
		t.Error("up must add the identity column as GENERATED BY DEFAULT")
	}
	if strings.Contains(up, "GENERATED ALWAYS") {
		t.Error("up must not convert any serial column to GENERATED ALWAYS")
	}

	// Sequence continuity: the old sequence's position is read after the
	// default is dropped (so nothing else can advance it) and before it is
	// dropped, then applied to the new identity sequence with is_called intact.
	steps := []string{
		"ALTER COLUMN id DROP DEFAULT",
		"SELECT last_value, is_called FROM %s",
		"DROP SEQUENCE %s",
		"ADD GENERATED BY DEFAULT AS IDENTITY",
		"PERFORM setval(pg_get_serial_sequence('public.' || quote_ident(target), 'id'), last_val, called)",
	}
	last := -1
	for _, step := range steps {
		at := strings.Index(up, step)
		if at < 0 {
			t.Fatalf("up missing continuity step %q", step)
		}
		if at < last {
			t.Errorf("up continuity step %q is out of order", step)
		}
		last = at
	}

	// The Down mirrors it: read the identity sequence, drop the identity,
	// recreate a sequence of the column's own type, position it, re-point the
	// default at it.
	last = -1
	for _, step := range []string{
		"SELECT last_value, is_called FROM %s",
		"ALTER COLUMN id DROP IDENTITY",
		"CREATE SEQUENCE public.%I AS %s OWNED BY public.%I.id",
		"PERFORM setval(format('public.%I', seq_name)::regclass, last_val, called)",
		"ALTER COLUMN id SET DEFAULT nextval(%L)",
	} {
		at := strings.Index(down, step)
		if at < 0 {
			t.Fatalf("down missing continuity step %q", step)
		}
		if at < last {
			t.Errorf("down continuity step %q is out of order", step)
		}
		last = at
	}

	// Idempotence guards: a column already in the target state is skipped, and
	// a table that vanished is an error rather than silently ignored.
	for _, want := range []string{
		"IF identity_kind IS NULL THEN RAISE EXCEPTION",
		"IF identity_kind <> '' THEN CONTINUE;",
	} {
		if !strings.Contains(up, want) {
			t.Errorf("up missing guard %q", want)
		}
	}
	if !strings.Contains(down, "IF identity_kind = '' THEN CONTINUE;") {
		t.Error("down missing already-serial skip guard")
	}
}

type varcharColumn struct {
	table  string
	column string
	length int
}

// varcharToTextColumns is the complete audit of character_maximum_length IS
// NOT NULL after the full chain, with the original lengths the Down restores.
var varcharToTextColumns = []varcharColumn{
	{"notification_server_channels", "name", 64},
	{"notification_server_channels", "url_host", 253},
	{"notification_server_channels", "disabled_reason", 256},
	{"notification_server_channels", "last_failure_message", 256},
	{"notification_webhooks", "name", 64},
	{"notification_webhooks", "url_host", 253},
	{"notification_webhooks", "disabled_reason", 256},
	{"notification_webhooks", "last_failure_message", 256},
	{"push_delivery_attempts", "upstream_reason", 256},
	{"push_delivery_attempts", "failure_message", 256},
	{"push_devices", "device_id", 128},
	{"web_push_delivery_attempts", "failure_message", 256},
	{"web_push_subscriptions", "device_name", 128},
	{"webhook_delivery_attempts", "failure_message", 256},
}

func TestVarcharToTextMigrationContract(t *testing.T) {
	up, down := readMigrationSections(t, varcharToTextMigration)

	if got, want := strings.Count(up, "TYPE text"), len(varcharToTextColumns); got != want {
		t.Fatalf("up converts %d columns, contract lists %d: update this test alongside the migration", got, want)
	}
	if got, want := strings.Count(down, "TYPE character varying("), len(varcharToTextColumns); got != want {
		t.Fatalf("down restores %d columns, contract lists %d", got, want)
	}

	for _, c := range varcharToTextColumns {
		alter := fmt.Sprintf("ALTER COLUMN %s TYPE text", c.column)
		// The ALTER TABLE for this column's table must precede the ALTER
		// COLUMN, and no other table's ALTER may sit between them.
		if !columnAlteredOn(up, c.table, alter) {
			t.Errorf("up missing %q on public.%s", alter, c.table)
		}
		restore := fmt.Sprintf("ALTER COLUMN %s TYPE character varying(%d)", c.column, c.length)
		if !columnAlteredOn(down, c.table, restore) {
			t.Errorf("down missing %q on public.%s", restore, c.table)
		}
	}

	// A USING clause or a CHECK would turn a catalog-only change into a
	// rewrite or a new rule; neither belongs here.
	for _, forbidden := range []string{" USING ", "ADD CONSTRAINT", "CHECK ("} {
		if strings.Contains(up, forbidden) {
			t.Errorf("up must stay a metadata-only ALTER TYPE; found %q", forbidden)
		}
	}

	// device_name's DEFAULT is the one literal that has to follow the type.
	if !strings.Contains(up, "ALTER COLUMN device_name SET DEFAULT ''::text") {
		t.Error("up must re-express web_push_subscriptions.device_name's default as text")
	}
	if !strings.Contains(down, "ALTER COLUMN device_name SET DEFAULT ''::character varying") {
		t.Error("down must restore web_push_subscriptions.device_name's varchar default")
	}
}

// columnAlteredOn reports whether alter appears inside an ALTER TABLE
// public.<table> statement in body.
func columnAlteredOn(body, table, alter string) bool {
	for _, stmt := range strings.Split(body, ";") {
		stmt = strings.TrimSpace(stmt)
		if strings.HasPrefix(stmt, "ALTER TABLE public."+table+" ") && strings.Contains(stmt, alter) {
			return true
		}
	}
	return false
}

type renamePair struct {
	from, to string
	// indexes and constraints named after the table, keyed old -> new.
	indexes     map[string]string
	constraints map[string]string
}

var renamePairs = []renamePair{
	{
		from: "oauth_session", to: "oauth_sessions",
		indexes: map[string]string{
			"oauth_session_pkey":        "oauth_sessions_pkey",
			"oauth_session_expires_idx": "oauth_sessions_expires_idx",
		},
	},
	{
		from: "oauth_completion", to: "oauth_completions",
		indexes: map[string]string{
			"oauth_completion_pkey":        "oauth_completions_pkey",
			"oauth_completion_expires_idx": "oauth_completions_expires_idx",
		},
	},
	{
		// Scope qualifier leads, matching admin_jobs / admin_dashboard_layouts
		// and the user_* family (including user_watch_history, which this
		// table is the server-scope sibling of).
		from: "playback_history_admin", to: "admin_playback_history",
		indexes: map[string]string{
			"playback_history_admin_pkey":                   "admin_playback_history_pkey",
			"idx_playback_history_admin_ended":              "idx_admin_playback_history_ended",
			"idx_playback_history_admin_started":            "idx_admin_playback_history_started",
			"idx_playback_history_admin_user_ended":         "idx_admin_playback_history_user_ended",
			"idx_playback_history_admin_user_profile_ended": "idx_admin_playback_history_user_profile_ended",
		},
		constraints: map[string]string{
			"playback_history_admin_user_id_fkey": "admin_playback_history_user_id_fkey",
		},
	},
}

func TestRenameTablesMigrationContract(t *testing.T) {
	up, down := readMigrationSections(t, renameTablesMigration)

	if got, want := strings.Count(up, "ALTER TABLE public.")-strings.Count(up, "RENAME CONSTRAINT"), len(renamePairs); got != want {
		t.Fatalf("up renames %d tables, contract lists %d: update this test alongside the migration", got, want)
	}

	for _, p := range renamePairs {
		upTable := fmt.Sprintf("ALTER TABLE public.%s RENAME TO %s;", p.from, p.to)
		if !strings.Contains(up, upTable) {
			t.Errorf("up missing %q", upTable)
		}
		downTable := fmt.Sprintf("ALTER TABLE public.%s RENAME TO %s;", p.to, p.from)
		if !strings.Contains(down, downTable) {
			t.Errorf("down missing %q", downTable)
		}
		for oldIdx, newIdx := range p.indexes {
			if want := fmt.Sprintf("ALTER INDEX public.%s RENAME TO %s;", oldIdx, newIdx); !strings.Contains(up, want) {
				t.Errorf("up missing %q", want)
			}
			if want := fmt.Sprintf("ALTER INDEX public.%s RENAME TO %s;", newIdx, oldIdx); !strings.Contains(down, want) {
				t.Errorf("down missing %q", want)
			}
		}
		for oldCon, newCon := range p.constraints {
			if want := fmt.Sprintf("ALTER TABLE public.%s RENAME CONSTRAINT %s TO %s;", p.to, oldCon, newCon); !strings.Contains(up, want) {
				t.Errorf("up missing %q", want)
			}
			if want := fmt.Sprintf("ALTER TABLE public.%s RENAME CONSTRAINT %s TO %s;", p.to, newCon, oldCon); !strings.Contains(down, want) {
				t.Errorf("down missing %q", want)
			}
		}
		// Postgres 18 materializes NOT NULL as named constraints that RENAME
		// TABLE leaves behind; both directions sweep them by prefix.
		for _, section := range []string{up, down} {
			if !strings.Contains(section, fmt.Sprintf("('%s', '%s')", p.from, p.to)) &&
				!strings.Contains(section, fmt.Sprintf("('%s', '%s')", p.to, p.from)) {
				t.Errorf("NOT NULL constraint sweep does not list the %s/%s pair", p.from, p.to)
			}
		}
	}
	if !strings.Contains(up, "contype = 'n'") || !strings.Contains(down, "contype = 'n'") {
		t.Error("both sections must sweep the NOT NULL (contype 'n') constraints")
	}

	// No data or shape change rides along with the rename.
	for _, forbidden := range []string{"CREATE TABLE", "DROP TABLE", "INSERT", "UPDATE ", "DELETE", "ADD COLUMN", "DROP COLUMN"} {
		if strings.Contains(up, forbidden) || strings.Contains(down, forbidden) {
			t.Errorf("rename migration must not contain %q", forbidden)
		}
	}
}
