/**
 * This file was auto-generated by scripts/generate-apiv2.mjs from
 * contracts/api/v2/openapi.json. Do not make direct changes to the file.
 */

/** Operation ids keyed by `METHOD /path`, as the committed v2 OpenAPI document lists them. */
export const v2Operations = {
  "DELETE /api/v2/profile/sections": "resetProfileSectionOverrides",
  "DELETE /api/v2/profiles/{id}": "deleteProfile",
  "DELETE /api/v2/profiles/{id}/avatar": "deleteProfileAvatar",
  "DELETE /api/v2/settings/device/subtitle-appearance": "deleteSubtitleAppearanceDeviceOverride",
  "DELETE /api/v2/settings/values/{key}": "deleteSettingValue",
  "GET /api/v2/account/me": "getCurrentUser",
  "GET /api/v2/admin/users": "listAdminUsers",
  "GET /api/v2/openapi.json": "getOpenAPIDocument",
  "GET /api/v2/profile/sections": "listProfileSectionOverrides",
  "GET /api/v2/profile/sections/flags": "getProfileSectionFlags",
  "GET /api/v2/profile/sections/settings": "getProfileSectionSettings",
  "GET /api/v2/profiles": "listProfiles",
  "GET /api/v2/profiles/household/sessions": "listHouseholdSessions",
  "GET /api/v2/progress": "listProgress",
  "GET /api/v2/settings/contract": "getSettingsContract",
  "GET /api/v2/settings/contract/capabilities": "getSettingsContractCapabilities",
  "GET /api/v2/settings/overlay-config": "getOverlayConfig",
  "GET /api/v2/settings/plugins": "listPluginSettings",
  "GET /api/v2/settings/plugins/{installation_id}": "getPluginSettings",
  "GET /api/v2/settings/subtitle-appearance/effective": "getEffectiveSubtitleAppearance",
  "GET /api/v2/settings/values": "listSettingValues",
  "GET /api/v2/settings/values/effective": "listEffectiveSettings",
  "GET /api/v2/settings/values/{key}": "getSettingValue",
  "GET /api/v2/system/info": "getSystemInfo",
  "GET /api/v2/system/setup": "getSetupStatus",
  "PATCH /api/v2/profiles/{id}": "updateProfile",
  "POST /api/v2/profiles": "createProfile",
  "POST /api/v2/profiles/{id}/verify-pin": "verifyProfilePIN",
  "POST /api/v2/settings/values/effective": "resolveEffectiveSettings",
  "PUT /api/v2/profile/sections": "replaceProfileSectionOverrides",
  "PUT /api/v2/profiles/{id}/avatar": "uploadProfileAvatar",
  "PUT /api/v2/settings/device/subtitle-appearance": "updateSubtitleAppearanceDeviceOverride",
  "PUT /api/v2/settings/plugins/{installation_id}": "updatePluginSettings",
  "PUT /api/v2/settings/values/nav.shortcuts/item": "updateNavigationShortcut",
  "PUT /api/v2/settings/values/{key}": "updateSettingValue",
} as const;
