/**
 * This file was auto-generated by scripts/generate-apiv2.mjs from
 * contracts/api/v2/openapi.json. Do not make direct changes to the file.
 */

/** Operation ids keyed by `METHOD /path`, as the committed v2 OpenAPI document lists them. */
export const v2Operations = {
  "DELETE /api/v2/audio-prefs/{series_id}": "deleteAudioPreference",
  "DELETE /api/v2/library-playback-prefs/{library_id}": "deleteLibraryPlaybackPreference",
  "DELETE /api/v2/profile/sections": "resetProfileSectionOverrides",
  "DELETE /api/v2/profiles/{id}": "deleteProfile",
  "DELETE /api/v2/profiles/{id}/avatar": "deleteProfileAvatar",
  "DELETE /api/v2/subtitle-prefs/{series_id}": "deleteSubtitlePreference",
  "GET /api/v2/account/me": "getCurrentUser",
  "GET /api/v2/admin/users": "listAdminUsers",
  "GET /api/v2/audio-prefs/{series_id}": "getAudioPreference",
  "GET /api/v2/library-playback-prefs": "listLibraryPlaybackPreferences",
  "GET /api/v2/openapi.json": "getOpenAPIDocument",
  "GET /api/v2/profile/sections": "listProfileSectionOverrides",
  "GET /api/v2/profile/sections/flags": "getProfileSectionFlags",
  "GET /api/v2/profile/sections/settings": "getProfileSectionSettings",
  "GET /api/v2/profiles": "listProfiles",
  "GET /api/v2/profiles/household/sessions": "listHouseholdSessions",
  "GET /api/v2/progress": "listProgress",
  "GET /api/v2/subtitle-prefs/{series_id}": "getSubtitlePreference",
  "GET /api/v2/system/info": "getSystemInfo",
  "GET /api/v2/system/setup": "getSetupStatus",
  "PATCH /api/v2/library-playback-prefs/{library_id}": "updateLibraryPlaybackPreference",
  "PATCH /api/v2/profiles/{id}": "updateProfile",
  "POST /api/v2/profiles": "createProfile",
  "POST /api/v2/profiles/{id}/verify-pin": "verifyProfilePIN",
  "PUT /api/v2/audio-prefs/{series_id}": "updateAudioPreference",
  "PUT /api/v2/profile/sections": "replaceProfileSectionOverrides",
  "PUT /api/v2/profiles/{id}/avatar": "uploadProfileAvatar",
  "PUT /api/v2/subtitle-prefs/{series_id}": "updateSubtitlePreference",
} as const;
