// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/auth_provider.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_silo_plugin_v1_auth_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_auth_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_auth_provider_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthenticateRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AuthenticateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExternalSubject string                 `protobuf:"bytes,1,opt,name=external_subject,json=externalSubject,proto3" json:"external_subject,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Claims          *structpb.Struct       `protobuf:"bytes,4,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_silo_plugin_v1_auth_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_auth_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_auth_provider_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetExternalSubject() string {
	if x != nil {
		return x.ExternalSubject
	}
	return ""
}

func (x *AuthenticateResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AuthenticateResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthenticateResponse) GetClaims() *structpb.Struct {
	if x != nil {
		return x.Claims
	}
	return nil
}

type InitAuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectUri   string                 `protobuf:"bytes,1,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Linking       bool                   `protobuf:"varint,3,opt,name=linking,proto3" json:"linking,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAuthorizeRequest) Reset() {
	*x = InitAuthorizeRequest{}
	mi := &file_silo_plugin_v1_auth_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAuthorizeRequest) ProtoMessage() {}

func (x *InitAuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_auth_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAuthorizeRequest.ProtoReflect.Descriptor instead.
func (*InitAuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_auth_provider_proto_rawDescGZIP(), []int{2}
}

func (x *InitAuthorizeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *InitAuthorizeRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InitAuthorizeRequest) GetLinking() bool {
	if x != nil {
		return x.Linking
	}
	return false
}

func (x *InitAuthorizeRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InitAuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorizeUrl  string                 `protobuf:"bytes,1,opt,name=authorize_url,json=authorizeUrl,proto3" json:"authorize_url,omitempty"`
	ProviderState *structpb.Struct       `protobuf:"bytes,2,opt,name=provider_state,json=providerState,proto3" json:"provider_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAuthorizeResponse) Reset() {
	*x = InitAuthorizeResponse{}
	mi := &file_silo_plugin_v1_auth_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAuthorizeResponse) ProtoMessage() {}

func (x *InitAuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_auth_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAuthorizeResponse.ProtoReflect.Descriptor instead.
func (*InitAuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_auth_provider_proto_rawDescGZIP(), []int{3}
}

func (x *InitAuthorizeResponse) GetAuthorizeUrl() string {
	if x != nil {
		return x.AuthorizeUrl
	}
	return ""
}

func (x *InitAuthorizeResponse) GetProviderState() *structpb.Struct {
	if x != nil {
		return x.ProviderState
	}
	return nil
}

type ExchangeCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	ProviderState *structpb.Struct       `protobuf:"bytes,4,opt,name=provider_state,json=providerState,proto3" json:"provider_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeCodeRequest) Reset() {
	*x = ExchangeCodeRequest{}
	mi := &file_silo_plugin_v1_auth_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCodeRequest) ProtoMessage() {}

func (x *ExchangeCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_auth_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCodeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeCodeRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_auth_provider_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExchangeCodeRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ExchangeCodeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *ExchangeCodeRequest) GetProviderState() *structpb.Struct {
	if x != nil {
		return x.ProviderState
	}
	return nil
}

type RefreshSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExternalSubject string                 `protobuf:"bytes,1,opt,name=external_subject,json=externalSubject,proto3" json:"external_subject,omitempty"`
	RefreshState    *structpb.Struct       `protobuf:"bytes,2,opt,name=refresh_state,json=refreshState,proto3" json:"refresh_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefreshSessionRequest) Reset() {
	*x = RefreshSessionRequest{}
	mi := &file_silo_plugin_v1_auth_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionRequest) ProtoMessage() {}

func (x *RefreshSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_auth_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshSessionRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_auth_provider_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshSessionRequest) GetExternalSubject() string {
	if x != nil {
		return x.ExternalSubject
	}
	return ""
}

func (x *RefreshSessionRequest) GetRefreshState() *structpb.Struct {
	if x != nil {
		return x.RefreshState
	}
	return nil
}

var File_silo_plugin_v1_auth_provider_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_auth_provider_proto_rawDesc = "" +
	"\n" +
	"\"silo/plugin/v1/auth_provider.proto\x12\x0esilo.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x82\x01\n" +
	"\x13AuthenticateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xab\x01\n" +
	"\x14AuthenticateResponse\x12)\n" +
	"\x10external_subject\x18\x01 \x01(\tR\x0fexternalSubject\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12/\n" +
	"\x06claims\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06claims\"\x9e\x01\n" +
	"\x14InitAuthorizeRequest\x12!\n" +
	"\fredirect_uri\x18\x01 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\alinking\x18\x03 \x01(\bR\alinking\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"|\n" +
	"\x15InitAuthorizeResponse\x12#\n" +
	"\rauthorize_url\x18\x01 \x01(\tR\fauthorizeUrl\x12>\n" +
	"\x0eprovider_state\x18\x02 \x01(\v2\x17.google.protobuf.StructR\rproviderState\"\xa2\x01\n" +
	"\x13ExchangeCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\x12>\n" +
	"\x0eprovider_state\x18\x04 \x01(\v2\x17.google.protobuf.StructR\rproviderState\"\x80\x01\n" +
	"\x15RefreshSessionRequest\x12)\n" +
	"\x10external_subject\x18\x01 \x01(\tR\x0fexternalSubject\x12<\n" +
	"\rrefresh_state\x18\x02 \x01(\v2\x17.google.protobuf.StructR\frefreshState2\x81\x03\n" +
	"\fAuthProvider\x12Y\n" +
	"\fAuthenticate\x12#.silo.plugin.v1.AuthenticateRequest\x1a$.silo.plugin.v1.AuthenticateResponse\x12\\\n" +
	"\rInitAuthorize\x12$.silo.plugin.v1.InitAuthorizeRequest\x1a%.silo.plugin.v1.InitAuthorizeResponse\x12Y\n" +
	"\fExchangeCode\x12#.silo.plugin.v1.ExchangeCodeRequest\x1a$.silo.plugin.v1.AuthenticateResponse\x12]\n" +
	"\x0eRefreshSession\x12%.silo.plugin.v1.RefreshSessionRequest\x1a$.silo.plugin.v1.AuthenticateResponseBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_auth_provider_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_auth_provider_proto_rawDescData []byte
)

func file_silo_plugin_v1_auth_provider_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_auth_provider_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_auth_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_auth_provider_proto_rawDesc), len(file_silo_plugin_v1_auth_provider_proto_rawDesc)))
	})
	return file_silo_plugin_v1_auth_provider_proto_rawDescData
}

var file_silo_plugin_v1_auth_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_silo_plugin_v1_auth_provider_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),   // 0: silo.plugin.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),  // 1: silo.plugin.v1.AuthenticateResponse
	(*InitAuthorizeRequest)(nil),  // 2: silo.plugin.v1.InitAuthorizeRequest
	(*InitAuthorizeResponse)(nil), // 3: silo.plugin.v1.InitAuthorizeResponse
	(*ExchangeCodeRequest)(nil),   // 4: silo.plugin.v1.ExchangeCodeRequest
	(*RefreshSessionRequest)(nil), // 5: silo.plugin.v1.RefreshSessionRequest
	(*structpb.Struct)(nil),       // 6: google.protobuf.Struct
}
var file_silo_plugin_v1_auth_provider_proto_depIdxs = []int32{
	6,  // 0: silo.plugin.v1.AuthenticateRequest.metadata:type_name -> google.protobuf.Struct
	6,  // 1: silo.plugin.v1.AuthenticateResponse.claims:type_name -> google.protobuf.Struct
	6,  // 2: silo.plugin.v1.InitAuthorizeRequest.metadata:type_name -> google.protobuf.Struct
	6,  // 3: silo.plugin.v1.InitAuthorizeResponse.provider_state:type_name -> google.protobuf.Struct
	6,  // 4: silo.plugin.v1.ExchangeCodeRequest.provider_state:type_name -> google.protobuf.Struct
	6,  // 5: silo.plugin.v1.RefreshSessionRequest.refresh_state:type_name -> google.protobuf.Struct
	0,  // 6: silo.plugin.v1.AuthProvider.Authenticate:input_type -> silo.plugin.v1.AuthenticateRequest
	2,  // 7: silo.plugin.v1.AuthProvider.InitAuthorize:input_type -> silo.plugin.v1.InitAuthorizeRequest
	4,  // 8: silo.plugin.v1.AuthProvider.ExchangeCode:input_type -> silo.plugin.v1.ExchangeCodeRequest
	5,  // 9: silo.plugin.v1.AuthProvider.RefreshSession:input_type -> silo.plugin.v1.RefreshSessionRequest
	1,  // 10: silo.plugin.v1.AuthProvider.Authenticate:output_type -> silo.plugin.v1.AuthenticateResponse
	3,  // 11: silo.plugin.v1.AuthProvider.InitAuthorize:output_type -> silo.plugin.v1.InitAuthorizeResponse
	1,  // 12: silo.plugin.v1.AuthProvider.ExchangeCode:output_type -> silo.plugin.v1.AuthenticateResponse
	1,  // 13: silo.plugin.v1.AuthProvider.RefreshSession:output_type -> silo.plugin.v1.AuthenticateResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_auth_provider_proto_init() }
func file_silo_plugin_v1_auth_provider_proto_init() {
	if File_silo_plugin_v1_auth_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_auth_provider_proto_rawDesc), len(file_silo_plugin_v1_auth_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_auth_provider_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_auth_provider_proto_depIdxs,
		MessageInfos:      file_silo_plugin_v1_auth_provider_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_auth_provider_proto = out.File
	file_silo_plugin_v1_auth_provider_proto_goTypes = nil
	file_silo_plugin_v1_auth_provider_proto_depIdxs = nil
}
