// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/event_consumer.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandleEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleEventRequest) Reset() {
	*x = HandleEventRequest{}
	mi := &file_silo_plugin_v1_event_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleEventRequest) ProtoMessage() {}

func (x *HandleEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_event_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleEventRequest.ProtoReflect.Descriptor instead.
func (*HandleEventRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_event_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *HandleEventRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *HandleEventRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HandleEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleEventResponse) Reset() {
	*x = HandleEventResponse{}
	mi := &file_silo_plugin_v1_event_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleEventResponse) ProtoMessage() {}

func (x *HandleEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_event_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleEventResponse.ProtoReflect.Descriptor instead.
func (*HandleEventResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_event_consumer_proto_rawDescGZIP(), []int{1}
}

var File_silo_plugin_v1_event_consumer_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_event_consumer_proto_rawDesc = "" +
	"\n" +
	"#silo/plugin/v1/event_consumer.proto\x12\x0esilo.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"f\n" +
	"\x12HandleEventRequest\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\"\x15\n" +
	"\x13HandleEventResponse2g\n" +
	"\rEventConsumer\x12V\n" +
	"\vHandleEvent\x12\".silo.plugin.v1.HandleEventRequest\x1a#.silo.plugin.v1.HandleEventResponseBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_event_consumer_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_event_consumer_proto_rawDescData []byte
)

func file_silo_plugin_v1_event_consumer_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_event_consumer_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_event_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_event_consumer_proto_rawDesc), len(file_silo_plugin_v1_event_consumer_proto_rawDesc)))
	})
	return file_silo_plugin_v1_event_consumer_proto_rawDescData
}

var file_silo_plugin_v1_event_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_silo_plugin_v1_event_consumer_proto_goTypes = []any{
	(*HandleEventRequest)(nil),  // 0: silo.plugin.v1.HandleEventRequest
	(*HandleEventResponse)(nil), // 1: silo.plugin.v1.HandleEventResponse
	(*structpb.Struct)(nil),     // 2: google.protobuf.Struct
}
var file_silo_plugin_v1_event_consumer_proto_depIdxs = []int32{
	2, // 0: silo.plugin.v1.HandleEventRequest.payload:type_name -> google.protobuf.Struct
	0, // 1: silo.plugin.v1.EventConsumer.HandleEvent:input_type -> silo.plugin.v1.HandleEventRequest
	1, // 2: silo.plugin.v1.EventConsumer.HandleEvent:output_type -> silo.plugin.v1.HandleEventResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_event_consumer_proto_init() }
func file_silo_plugin_v1_event_consumer_proto_init() {
	if File_silo_plugin_v1_event_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_event_consumer_proto_rawDesc), len(file_silo_plugin_v1_event_consumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_event_consumer_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_event_consumer_proto_depIdxs,
		MessageInfos:      file_silo_plugin_v1_event_consumer_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_event_consumer_proto = out.File
	file_silo_plugin_v1_event_consumer_proto_goTypes = nil
	file_silo_plugin_v1_event_consumer_proto_depIdxs = nil
}
