// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/event_consumer.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventConsumer_HandleEvent_FullMethodName = "/silo.plugin.v1.EventConsumer/HandleEvent"
)

// EventConsumerClient is the client API for EventConsumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventConsumerClient interface {
	HandleEvent(ctx context.Context, in *HandleEventRequest, opts ...grpc.CallOption) (*HandleEventResponse, error)
}

type eventConsumerClient struct {
	cc grpc.ClientConnInterface
}

func NewEventConsumerClient(cc grpc.ClientConnInterface) EventConsumerClient {
	return &eventConsumerClient{cc}
}

func (c *eventConsumerClient) HandleEvent(ctx context.Context, in *HandleEventRequest, opts ...grpc.CallOption) (*HandleEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleEventResponse)
	err := c.cc.Invoke(ctx, EventConsumer_HandleEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventConsumerServer is the server API for EventConsumer service.
// All implementations should embed UnimplementedEventConsumerServer
// for forward compatibility.
type EventConsumerServer interface {
	HandleEvent(context.Context, *HandleEventRequest) (*HandleEventResponse, error)
}

// UnimplementedEventConsumerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventConsumerServer struct{}

func (UnimplementedEventConsumerServer) HandleEvent(context.Context, *HandleEventRequest) (*HandleEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleEvent not implemented")
}
func (UnimplementedEventConsumerServer) testEmbeddedByValue() {}

// UnsafeEventConsumerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventConsumerServer will
// result in compilation errors.
type UnsafeEventConsumerServer interface {
	mustEmbedUnimplementedEventConsumerServer()
}

func RegisterEventConsumerServer(s grpc.ServiceRegistrar, srv EventConsumerServer) {
	// If the following call panics, it indicates UnimplementedEventConsumerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventConsumer_ServiceDesc, srv)
}

func _EventConsumer_HandleEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventConsumerServer).HandleEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventConsumer_HandleEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventConsumerServer).HandleEvent(ctx, req.(*HandleEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventConsumer_ServiceDesc is the grpc.ServiceDesc for EventConsumer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventConsumer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.EventConsumer",
	HandlerType: (*EventConsumerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleEvent",
			Handler:    _EventConsumer_HandleEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/event_consumer.proto",
}
