// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/http_routes.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandleHTTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Query         *structpb.Struct       `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleHTTPRequest) Reset() {
	*x = HandleHTTPRequest{}
	mi := &file_silo_plugin_v1_http_routes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleHTTPRequest) ProtoMessage() {}

func (x *HandleHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_http_routes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleHTTPRequest.ProtoReflect.Descriptor instead.
func (*HandleHTTPRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_http_routes_proto_rawDescGZIP(), []int{0}
}

func (x *HandleHTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HandleHTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HandleHTTPRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HandleHTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HandleHTTPRequest) GetQuery() *structpb.Struct {
	if x != nil {
		return x.Query
	}
	return nil
}

type HandleHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleHTTPResponse) Reset() {
	*x = HandleHTTPResponse{}
	mi := &file_silo_plugin_v1_http_routes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleHTTPResponse) ProtoMessage() {}

func (x *HandleHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_http_routes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleHTTPResponse.ProtoReflect.Descriptor instead.
func (*HandleHTTPResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_http_routes_proto_rawDescGZIP(), []int{1}
}

func (x *HandleHTTPResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HandleHTTPResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HandleHTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_silo_plugin_v1_http_routes_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_http_routes_proto_rawDesc = "" +
	"\n" +
	" silo/plugin/v1/http_routes.proto\x12\x0esilo.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x88\x02\n" +
	"\x11HandleHTTPRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12H\n" +
	"\aheaders\x18\x03 \x03(\v2..silo.plugin.v1.HandleHTTPRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12-\n" +
	"\x05query\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x05query\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\x12HandleHTTPResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12I\n" +
	"\aheaders\x18\x02 \x03(\v2/.silo.plugin.v1.HandleHTTPResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012]\n" +
	"\n" +
	"HttpRoutes\x12O\n" +
	"\x06Handle\x12!.silo.plugin.v1.HandleHTTPRequest\x1a\".silo.plugin.v1.HandleHTTPResponseBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_http_routes_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_http_routes_proto_rawDescData []byte
)

func file_silo_plugin_v1_http_routes_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_http_routes_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_http_routes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_http_routes_proto_rawDesc), len(file_silo_plugin_v1_http_routes_proto_rawDesc)))
	})
	return file_silo_plugin_v1_http_routes_proto_rawDescData
}

var file_silo_plugin_v1_http_routes_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_silo_plugin_v1_http_routes_proto_goTypes = []any{
	(*HandleHTTPRequest)(nil),  // 0: silo.plugin.v1.HandleHTTPRequest
	(*HandleHTTPResponse)(nil), // 1: silo.plugin.v1.HandleHTTPResponse
	nil,                        // 2: silo.plugin.v1.HandleHTTPRequest.HeadersEntry
	nil,                        // 3: silo.plugin.v1.HandleHTTPResponse.HeadersEntry
	(*structpb.Struct)(nil),    // 4: google.protobuf.Struct
}
var file_silo_plugin_v1_http_routes_proto_depIdxs = []int32{
	2, // 0: silo.plugin.v1.HandleHTTPRequest.headers:type_name -> silo.plugin.v1.HandleHTTPRequest.HeadersEntry
	4, // 1: silo.plugin.v1.HandleHTTPRequest.query:type_name -> google.protobuf.Struct
	3, // 2: silo.plugin.v1.HandleHTTPResponse.headers:type_name -> silo.plugin.v1.HandleHTTPResponse.HeadersEntry
	0, // 3: silo.plugin.v1.HttpRoutes.Handle:input_type -> silo.plugin.v1.HandleHTTPRequest
	1, // 4: silo.plugin.v1.HttpRoutes.Handle:output_type -> silo.plugin.v1.HandleHTTPResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_http_routes_proto_init() }
func file_silo_plugin_v1_http_routes_proto_init() {
	if File_silo_plugin_v1_http_routes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_http_routes_proto_rawDesc), len(file_silo_plugin_v1_http_routes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_http_routes_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_http_routes_proto_depIdxs,
		MessageInfos:      file_silo_plugin_v1_http_routes_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_http_routes_proto = out.File
	file_silo_plugin_v1_http_routes_proto_goTypes = nil
	file_silo_plugin_v1_http_routes_proto_depIdxs = nil
}
