// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/http_routes.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HttpRoutes_Handle_FullMethodName = "/silo.plugin.v1.HttpRoutes/Handle"
)

// HttpRoutesClient is the client API for HttpRoutes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HttpRoutesClient interface {
	Handle(ctx context.Context, in *HandleHTTPRequest, opts ...grpc.CallOption) (*HandleHTTPResponse, error)
}

type httpRoutesClient struct {
	cc grpc.ClientConnInterface
}

func NewHttpRoutesClient(cc grpc.ClientConnInterface) HttpRoutesClient {
	return &httpRoutesClient{cc}
}

func (c *httpRoutesClient) Handle(ctx context.Context, in *HandleHTTPRequest, opts ...grpc.CallOption) (*HandleHTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleHTTPResponse)
	err := c.cc.Invoke(ctx, HttpRoutes_Handle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HttpRoutesServer is the server API for HttpRoutes service.
// All implementations should embed UnimplementedHttpRoutesServer
// for forward compatibility.
type HttpRoutesServer interface {
	Handle(context.Context, *HandleHTTPRequest) (*HandleHTTPResponse, error)
}

// UnimplementedHttpRoutesServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHttpRoutesServer struct{}

func (UnimplementedHttpRoutesServer) Handle(context.Context, *HandleHTTPRequest) (*HandleHTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedHttpRoutesServer) testEmbeddedByValue() {}

// UnsafeHttpRoutesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HttpRoutesServer will
// result in compilation errors.
type UnsafeHttpRoutesServer interface {
	mustEmbedUnimplementedHttpRoutesServer()
}

func RegisterHttpRoutesServer(s grpc.ServiceRegistrar, srv HttpRoutesServer) {
	// If the following call panics, it indicates UnimplementedHttpRoutesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HttpRoutes_ServiceDesc, srv)
}

func _HttpRoutes_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleHTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpRoutesServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpRoutes_Handle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpRoutesServer).Handle(ctx, req.(*HandleHTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HttpRoutes_ServiceDesc is the grpc.ServiceDesc for HttpRoutes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HttpRoutes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.HttpRoutes",
	HandlerType: (*HttpRoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _HttpRoutes_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/http_routes.proto",
}
