// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/marker_provider.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarkerExternalIDs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmdbId        string                 `protobuf:"bytes,1,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	ImdbId        string                 `protobuf:"bytes,2,opt,name=imdb_id,json=imdbId,proto3" json:"imdb_id,omitempty"`
	TvdbId        string                 `protobuf:"bytes,3,opt,name=tvdb_id,json=tvdbId,proto3" json:"tvdb_id,omitempty"`
	ProviderIds   *structpb.Struct       `protobuf:"bytes,4,opt,name=provider_ids,json=providerIds,proto3" json:"provider_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkerExternalIDs) Reset() {
	*x = MarkerExternalIDs{}
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkerExternalIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerExternalIDs) ProtoMessage() {}

func (x *MarkerExternalIDs) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerExternalIDs.ProtoReflect.Descriptor instead.
func (*MarkerExternalIDs) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_marker_provider_proto_rawDescGZIP(), []int{0}
}

func (x *MarkerExternalIDs) GetTmdbId() string {
	if x != nil {
		return x.TmdbId
	}
	return ""
}

func (x *MarkerExternalIDs) GetImdbId() string {
	if x != nil {
		return x.ImdbId
	}
	return ""
}

func (x *MarkerExternalIDs) GetTvdbId() string {
	if x != nil {
		return x.TvdbId
	}
	return ""
}

func (x *MarkerExternalIDs) GetProviderIds() *structpb.Struct {
	if x != nil {
		return x.ProviderIds
	}
	return nil
}

type FetchMarkersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemType        string                 `protobuf:"bytes,1,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // "movie" | "episode"
	ExternalIds     *MarkerExternalIDs     `protobuf:"bytes,2,opt,name=external_ids,json=externalIds,proto3" json:"external_ids,omitempty"`
	SeasonNumber    int32                  `protobuf:"varint,3,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber   int32                  `protobuf:"varint,4,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FetchMarkersRequest) Reset() {
	*x = FetchMarkersRequest{}
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMarkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMarkersRequest) ProtoMessage() {}

func (x *FetchMarkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMarkersRequest.ProtoReflect.Descriptor instead.
func (*FetchMarkersRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_marker_provider_proto_rawDescGZIP(), []int{1}
}

func (x *FetchMarkersRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *FetchMarkersRequest) GetExternalIds() *MarkerExternalIDs {
	if x != nil {
		return x.ExternalIds
	}
	return nil
}

func (x *FetchMarkersRequest) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *FetchMarkersRequest) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *FetchMarkersRequest) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *FetchMarkersRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MarkerSegment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Segment         string                 `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"` // "intro" | "credits" | "recap" | "preview"
	StartSeconds    *float64               `protobuf:"fixed64,2,opt,name=start_seconds,json=startSeconds,proto3,oneof" json:"start_seconds,omitempty"`
	EndSeconds      *float64               `protobuf:"fixed64,3,opt,name=end_seconds,json=endSeconds,proto3,oneof" json:"end_seconds,omitempty"`
	Confidence      float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	SubmissionCount int32                  `protobuf:"varint,5,opt,name=submission_count,json=submissionCount,proto3" json:"submission_count,omitempty"`
	Algorithm       string                 `protobuf:"bytes,6,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkerSegment) Reset() {
	*x = MarkerSegment{}
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkerSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerSegment) ProtoMessage() {}

func (x *MarkerSegment) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerSegment.ProtoReflect.Descriptor instead.
func (*MarkerSegment) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_marker_provider_proto_rawDescGZIP(), []int{2}
}

func (x *MarkerSegment) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *MarkerSegment) GetStartSeconds() float64 {
	if x != nil && x.StartSeconds != nil {
		return *x.StartSeconds
	}
	return 0
}

func (x *MarkerSegment) GetEndSeconds() float64 {
	if x != nil && x.EndSeconds != nil {
		return *x.EndSeconds
	}
	return 0
}

func (x *MarkerSegment) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *MarkerSegment) GetSubmissionCount() int32 {
	if x != nil {
		return x.SubmissionCount
	}
	return 0
}

func (x *MarkerSegment) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *MarkerSegment) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FetchMarkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markers       []*MarkerSegment       `protobuf:"bytes,1,rep,name=markers,proto3" json:"markers,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMarkersResponse) Reset() {
	*x = FetchMarkersResponse{}
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMarkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMarkersResponse) ProtoMessage() {}

func (x *FetchMarkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMarkersResponse.ProtoReflect.Descriptor instead.
func (*FetchMarkersResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_marker_provider_proto_rawDescGZIP(), []int{3}
}

func (x *FetchMarkersResponse) GetMarkers() []*MarkerSegment {
	if x != nil {
		return x.Markers
	}
	return nil
}

func (x *FetchMarkersResponse) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SubmitMarkerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemType        string                 `protobuf:"bytes,1,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // "movie" | "episode"
	ExternalIds     *MarkerExternalIDs     `protobuf:"bytes,2,opt,name=external_ids,json=externalIds,proto3" json:"external_ids,omitempty"`
	SeasonNumber    int32                  `protobuf:"varint,3,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber   int32                  `protobuf:"varint,4,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	Segment         string                 `protobuf:"bytes,5,opt,name=segment,proto3" json:"segment,omitempty"` // "intro" | "credits" | "recap" | "preview"
	StartSeconds    *float64               `protobuf:"fixed64,6,opt,name=start_seconds,json=startSeconds,proto3,oneof" json:"start_seconds,omitempty"`
	EndSeconds      *float64               `protobuf:"fixed64,7,opt,name=end_seconds,json=endSeconds,proto3,oneof" json:"end_seconds,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,8,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitMarkerRequest) Reset() {
	*x = SubmitMarkerRequest{}
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMarkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMarkerRequest) ProtoMessage() {}

func (x *SubmitMarkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMarkerRequest.ProtoReflect.Descriptor instead.
func (*SubmitMarkerRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_marker_provider_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitMarkerRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *SubmitMarkerRequest) GetExternalIds() *MarkerExternalIDs {
	if x != nil {
		return x.ExternalIds
	}
	return nil
}

func (x *SubmitMarkerRequest) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *SubmitMarkerRequest) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *SubmitMarkerRequest) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *SubmitMarkerRequest) GetStartSeconds() float64 {
	if x != nil && x.StartSeconds != nil {
		return *x.StartSeconds
	}
	return 0
}

func (x *SubmitMarkerRequest) GetEndSeconds() float64 {
	if x != nil && x.EndSeconds != nil {
		return *x.EndSeconds
	}
	return 0
}

func (x *SubmitMarkerRequest) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *SubmitMarkerRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SubmitMarkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "pending" | "accepted" | "rejected"
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMarkerResponse) Reset() {
	*x = SubmitMarkerResponse{}
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMarkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMarkerResponse) ProtoMessage() {}

func (x *SubmitMarkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMarkerResponse.ProtoReflect.Descriptor instead.
func (*SubmitMarkerResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_marker_provider_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitMarkerResponse) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *SubmitMarkerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitMarkerResponse) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SubmitMarkerResponse) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetMarkerProviderStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarkerProviderStatsRequest) Reset() {
	*x = GetMarkerProviderStatsRequest{}
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarkerProviderStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarkerProviderStatsRequest) ProtoMessage() {}

func (x *GetMarkerProviderStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarkerProviderStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMarkerProviderStatsRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_marker_provider_proto_rawDescGZIP(), []int{6}
}

type MarkerProviderStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Total          int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Accepted       int32                  `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Pending        int32                  `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	Rejected       int32                  `protobuf:"varint,4,opt,name=rejected,proto3" json:"rejected,omitempty"`
	AcceptanceRate float64                `protobuf:"fixed64,5,opt,name=acceptance_rate,json=acceptanceRate,proto3" json:"acceptance_rate,omitempty"`
	CurrentStreak  int32                  `protobuf:"varint,6,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	BestStreak     int32                  `protobuf:"varint,7,opt,name=best_streak,json=bestStreak,proto3" json:"best_streak,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkerProviderStatsResponse) Reset() {
	*x = MarkerProviderStatsResponse{}
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkerProviderStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerProviderStatsResponse) ProtoMessage() {}

func (x *MarkerProviderStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_marker_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerProviderStatsResponse.ProtoReflect.Descriptor instead.
func (*MarkerProviderStatsResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_marker_provider_proto_rawDescGZIP(), []int{7}
}

func (x *MarkerProviderStatsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MarkerProviderStatsResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *MarkerProviderStatsResponse) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *MarkerProviderStatsResponse) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *MarkerProviderStatsResponse) GetAcceptanceRate() float64 {
	if x != nil {
		return x.AcceptanceRate
	}
	return 0
}

func (x *MarkerProviderStatsResponse) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *MarkerProviderStatsResponse) GetBestStreak() int32 {
	if x != nil {
		return x.BestStreak
	}
	return 0
}

func (x *MarkerProviderStatsResponse) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_silo_plugin_v1_marker_provider_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_marker_provider_proto_rawDesc = "" +
	"\n" +
	"$silo/plugin/v1/marker_provider.proto\x12\x0esilo.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x9a\x01\n" +
	"\x11MarkerExternalIDs\x12\x17\n" +
	"\atmdb_id\x18\x01 \x01(\tR\x06tmdbId\x12\x17\n" +
	"\aimdb_id\x18\x02 \x01(\tR\x06imdbId\x12\x17\n" +
	"\atvdb_id\x18\x03 \x01(\tR\x06tvdbId\x12:\n" +
	"\fprovider_ids\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vproviderIds\"\xa4\x02\n" +
	"\x13FetchMarkersRequest\x12\x1b\n" +
	"\titem_type\x18\x01 \x01(\tR\bitemType\x12D\n" +
	"\fexternal_ids\x18\x02 \x01(\v2!.silo.plugin.v1.MarkerExternalIDsR\vexternalIds\x12#\n" +
	"\rseason_number\x18\x03 \x01(\x05R\fseasonNumber\x12%\n" +
	"\x0eepisode_number\x18\x04 \x01(\x05R\repisodeNumber\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x01R\x0fdurationSeconds\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xb9\x02\n" +
	"\rMarkerSegment\x12\x18\n" +
	"\asegment\x18\x01 \x01(\tR\asegment\x12(\n" +
	"\rstart_seconds\x18\x02 \x01(\x01H\x00R\fstartSeconds\x88\x01\x01\x12$\n" +
	"\vend_seconds\x18\x03 \x01(\x01H\x01R\n" +
	"endSeconds\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12)\n" +
	"\x10submission_count\x18\x05 \x01(\x05R\x0fsubmissionCount\x12\x1c\n" +
	"\talgorithm\x18\x06 \x01(\tR\talgorithm\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadataB\x10\n" +
	"\x0e_start_secondsB\x0e\n" +
	"\f_end_seconds\"\x84\x01\n" +
	"\x14FetchMarkersResponse\x127\n" +
	"\amarkers\x18\x01 \x03(\v2\x1d.silo.plugin.v1.MarkerSegmentR\amarkers\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xb0\x03\n" +
	"\x13SubmitMarkerRequest\x12\x1b\n" +
	"\titem_type\x18\x01 \x01(\tR\bitemType\x12D\n" +
	"\fexternal_ids\x18\x02 \x01(\v2!.silo.plugin.v1.MarkerExternalIDsR\vexternalIds\x12#\n" +
	"\rseason_number\x18\x03 \x01(\x05R\fseasonNumber\x12%\n" +
	"\x0eepisode_number\x18\x04 \x01(\x05R\repisodeNumber\x12\x18\n" +
	"\asegment\x18\x05 \x01(\tR\asegment\x12(\n" +
	"\rstart_seconds\x18\x06 \x01(\x01H\x00R\fstartSeconds\x88\x01\x01\x12$\n" +
	"\vend_seconds\x18\a \x01(\x01H\x01R\n" +
	"endSeconds\x88\x01\x01\x12)\n" +
	"\x10duration_seconds\x18\b \x01(\x01R\x0fdurationSeconds\x123\n" +
	"\bmetadata\x18\t \x01(\v2\x17.google.protobuf.StructR\bmetadataB\x10\n" +
	"\x0e_start_secondsB\x0e\n" +
	"\f_end_seconds\"\xa0\x01\n" +
	"\x14SubmitMarkerResponse\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x1f\n" +
	"\x1dGetMarkerProviderStatsRequest\"\xab\x02\n" +
	"\x1bMarkerProviderStatsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x05R\baccepted\x12\x18\n" +
	"\apending\x18\x03 \x01(\x05R\apending\x12\x1a\n" +
	"\brejected\x18\x04 \x01(\x05R\brejected\x12'\n" +
	"\x0facceptance_rate\x18\x05 \x01(\x01R\x0eacceptanceRate\x12%\n" +
	"\x0ecurrent_streak\x18\x06 \x01(\x05R\rcurrentStreak\x12\x1f\n" +
	"\vbest_streak\x18\a \x01(\x05R\n" +
	"bestStreak\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata2\xbc\x02\n" +
	"\x0eMarkerProvider\x12Y\n" +
	"\fFetchMarkers\x12#.silo.plugin.v1.FetchMarkersRequest\x1a$.silo.plugin.v1.FetchMarkersResponse\x12Y\n" +
	"\fSubmitMarker\x12#.silo.plugin.v1.SubmitMarkerRequest\x1a$.silo.plugin.v1.SubmitMarkerResponse\x12t\n" +
	"\x16GetMarkerProviderStats\x12-.silo.plugin.v1.GetMarkerProviderStatsRequest\x1a+.silo.plugin.v1.MarkerProviderStatsResponseBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_marker_provider_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_marker_provider_proto_rawDescData []byte
)

func file_silo_plugin_v1_marker_provider_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_marker_provider_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_marker_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_marker_provider_proto_rawDesc), len(file_silo_plugin_v1_marker_provider_proto_rawDesc)))
	})
	return file_silo_plugin_v1_marker_provider_proto_rawDescData
}

var file_silo_plugin_v1_marker_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_silo_plugin_v1_marker_provider_proto_goTypes = []any{
	(*MarkerExternalIDs)(nil),             // 0: silo.plugin.v1.MarkerExternalIDs
	(*FetchMarkersRequest)(nil),           // 1: silo.plugin.v1.FetchMarkersRequest
	(*MarkerSegment)(nil),                 // 2: silo.plugin.v1.MarkerSegment
	(*FetchMarkersResponse)(nil),          // 3: silo.plugin.v1.FetchMarkersResponse
	(*SubmitMarkerRequest)(nil),           // 4: silo.plugin.v1.SubmitMarkerRequest
	(*SubmitMarkerResponse)(nil),          // 5: silo.plugin.v1.SubmitMarkerResponse
	(*GetMarkerProviderStatsRequest)(nil), // 6: silo.plugin.v1.GetMarkerProviderStatsRequest
	(*MarkerProviderStatsResponse)(nil),   // 7: silo.plugin.v1.MarkerProviderStatsResponse
	(*structpb.Struct)(nil),               // 8: google.protobuf.Struct
}
var file_silo_plugin_v1_marker_provider_proto_depIdxs = []int32{
	8,  // 0: silo.plugin.v1.MarkerExternalIDs.provider_ids:type_name -> google.protobuf.Struct
	0,  // 1: silo.plugin.v1.FetchMarkersRequest.external_ids:type_name -> silo.plugin.v1.MarkerExternalIDs
	8,  // 2: silo.plugin.v1.FetchMarkersRequest.metadata:type_name -> google.protobuf.Struct
	8,  // 3: silo.plugin.v1.MarkerSegment.metadata:type_name -> google.protobuf.Struct
	2,  // 4: silo.plugin.v1.FetchMarkersResponse.markers:type_name -> silo.plugin.v1.MarkerSegment
	8,  // 5: silo.plugin.v1.FetchMarkersResponse.metadata:type_name -> google.protobuf.Struct
	0,  // 6: silo.plugin.v1.SubmitMarkerRequest.external_ids:type_name -> silo.plugin.v1.MarkerExternalIDs
	8,  // 7: silo.plugin.v1.SubmitMarkerRequest.metadata:type_name -> google.protobuf.Struct
	8,  // 8: silo.plugin.v1.SubmitMarkerResponse.metadata:type_name -> google.protobuf.Struct
	8,  // 9: silo.plugin.v1.MarkerProviderStatsResponse.metadata:type_name -> google.protobuf.Struct
	1,  // 10: silo.plugin.v1.MarkerProvider.FetchMarkers:input_type -> silo.plugin.v1.FetchMarkersRequest
	4,  // 11: silo.plugin.v1.MarkerProvider.SubmitMarker:input_type -> silo.plugin.v1.SubmitMarkerRequest
	6,  // 12: silo.plugin.v1.MarkerProvider.GetMarkerProviderStats:input_type -> silo.plugin.v1.GetMarkerProviderStatsRequest
	3,  // 13: silo.plugin.v1.MarkerProvider.FetchMarkers:output_type -> silo.plugin.v1.FetchMarkersResponse
	5,  // 14: silo.plugin.v1.MarkerProvider.SubmitMarker:output_type -> silo.plugin.v1.SubmitMarkerResponse
	7,  // 15: silo.plugin.v1.MarkerProvider.GetMarkerProviderStats:output_type -> silo.plugin.v1.MarkerProviderStatsResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_marker_provider_proto_init() }
func file_silo_plugin_v1_marker_provider_proto_init() {
	if File_silo_plugin_v1_marker_provider_proto != nil {
		return
	}
	file_silo_plugin_v1_marker_provider_proto_msgTypes[2].OneofWrappers = []any{}
	file_silo_plugin_v1_marker_provider_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_marker_provider_proto_rawDesc), len(file_silo_plugin_v1_marker_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_marker_provider_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_marker_provider_proto_depIdxs,
		MessageInfos:      file_silo_plugin_v1_marker_provider_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_marker_provider_proto = out.File
	file_silo_plugin_v1_marker_provider_proto_goTypes = nil
	file_silo_plugin_v1_marker_provider_proto_depIdxs = nil
}
