// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/marker_provider.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarkerProvider_FetchMarkers_FullMethodName           = "/silo.plugin.v1.MarkerProvider/FetchMarkers"
	MarkerProvider_SubmitMarker_FullMethodName           = "/silo.plugin.v1.MarkerProvider/SubmitMarker"
	MarkerProvider_GetMarkerProviderStats_FullMethodName = "/silo.plugin.v1.MarkerProvider/GetMarkerProviderStats"
)

// MarkerProviderClient is the client API for MarkerProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarkerProviderClient interface {
	FetchMarkers(ctx context.Context, in *FetchMarkersRequest, opts ...grpc.CallOption) (*FetchMarkersResponse, error)
	SubmitMarker(ctx context.Context, in *SubmitMarkerRequest, opts ...grpc.CallOption) (*SubmitMarkerResponse, error)
	GetMarkerProviderStats(ctx context.Context, in *GetMarkerProviderStatsRequest, opts ...grpc.CallOption) (*MarkerProviderStatsResponse, error)
}

type markerProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewMarkerProviderClient(cc grpc.ClientConnInterface) MarkerProviderClient {
	return &markerProviderClient{cc}
}

func (c *markerProviderClient) FetchMarkers(ctx context.Context, in *FetchMarkersRequest, opts ...grpc.CallOption) (*FetchMarkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchMarkersResponse)
	err := c.cc.Invoke(ctx, MarkerProvider_FetchMarkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *markerProviderClient) SubmitMarker(ctx context.Context, in *SubmitMarkerRequest, opts ...grpc.CallOption) (*SubmitMarkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitMarkerResponse)
	err := c.cc.Invoke(ctx, MarkerProvider_SubmitMarker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *markerProviderClient) GetMarkerProviderStats(ctx context.Context, in *GetMarkerProviderStatsRequest, opts ...grpc.CallOption) (*MarkerProviderStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkerProviderStatsResponse)
	err := c.cc.Invoke(ctx, MarkerProvider_GetMarkerProviderStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarkerProviderServer is the server API for MarkerProvider service.
// All implementations should embed UnimplementedMarkerProviderServer
// for forward compatibility.
type MarkerProviderServer interface {
	FetchMarkers(context.Context, *FetchMarkersRequest) (*FetchMarkersResponse, error)
	SubmitMarker(context.Context, *SubmitMarkerRequest) (*SubmitMarkerResponse, error)
	GetMarkerProviderStats(context.Context, *GetMarkerProviderStatsRequest) (*MarkerProviderStatsResponse, error)
}

// UnimplementedMarkerProviderServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarkerProviderServer struct{}

func (UnimplementedMarkerProviderServer) FetchMarkers(context.Context, *FetchMarkersRequest) (*FetchMarkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchMarkers not implemented")
}
func (UnimplementedMarkerProviderServer) SubmitMarker(context.Context, *SubmitMarkerRequest) (*SubmitMarkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitMarker not implemented")
}
func (UnimplementedMarkerProviderServer) GetMarkerProviderStats(context.Context, *GetMarkerProviderStatsRequest) (*MarkerProviderStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarkerProviderStats not implemented")
}
func (UnimplementedMarkerProviderServer) testEmbeddedByValue() {}

// UnsafeMarkerProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarkerProviderServer will
// result in compilation errors.
type UnsafeMarkerProviderServer interface {
	mustEmbedUnimplementedMarkerProviderServer()
}

func RegisterMarkerProviderServer(s grpc.ServiceRegistrar, srv MarkerProviderServer) {
	// If the following call panics, it indicates UnimplementedMarkerProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarkerProvider_ServiceDesc, srv)
}

func _MarkerProvider_FetchMarkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchMarkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkerProviderServer).FetchMarkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkerProvider_FetchMarkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkerProviderServer).FetchMarkers(ctx, req.(*FetchMarkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarkerProvider_SubmitMarker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitMarkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkerProviderServer).SubmitMarker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkerProvider_SubmitMarker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkerProviderServer).SubmitMarker(ctx, req.(*SubmitMarkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarkerProvider_GetMarkerProviderStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarkerProviderStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkerProviderServer).GetMarkerProviderStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkerProvider_GetMarkerProviderStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkerProviderServer).GetMarkerProviderStats(ctx, req.(*GetMarkerProviderStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarkerProvider_ServiceDesc is the grpc.ServiceDesc for MarkerProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarkerProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.MarkerProvider",
	HandlerType: (*MarkerProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchMarkers",
			Handler:    _MarkerProvider_FetchMarkers_Handler,
		},
		{
			MethodName: "SubmitMarker",
			Handler:    _MarkerProvider_SubmitMarker_Handler,
		},
		{
			MethodName: "GetMarkerProviderStats",
			Handler:    _MarkerProvider_GetMarkerProviderStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/marker_provider.proto",
}
