// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/media_analyzer.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaAnalyzer_Analyze_FullMethodName = "/silo.plugin.v1.MediaAnalyzer/Analyze"
)

// MediaAnalyzerClient is the client API for MediaAnalyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaAnalyzerClient interface {
	Analyze(ctx context.Context, in *AnalyzeMediaRequest, opts ...grpc.CallOption) (*AnalyzeMediaResponse, error)
}

type mediaAnalyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaAnalyzerClient(cc grpc.ClientConnInterface) MediaAnalyzerClient {
	return &mediaAnalyzerClient{cc}
}

func (c *mediaAnalyzerClient) Analyze(ctx context.Context, in *AnalyzeMediaRequest, opts ...grpc.CallOption) (*AnalyzeMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeMediaResponse)
	err := c.cc.Invoke(ctx, MediaAnalyzer_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaAnalyzerServer is the server API for MediaAnalyzer service.
// All implementations should embed UnimplementedMediaAnalyzerServer
// for forward compatibility.
type MediaAnalyzerServer interface {
	Analyze(context.Context, *AnalyzeMediaRequest) (*AnalyzeMediaResponse, error)
}

// UnimplementedMediaAnalyzerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaAnalyzerServer struct{}

func (UnimplementedMediaAnalyzerServer) Analyze(context.Context, *AnalyzeMediaRequest) (*AnalyzeMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedMediaAnalyzerServer) testEmbeddedByValue() {}

// UnsafeMediaAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaAnalyzerServer will
// result in compilation errors.
type UnsafeMediaAnalyzerServer interface {
	mustEmbedUnimplementedMediaAnalyzerServer()
}

func RegisterMediaAnalyzerServer(s grpc.ServiceRegistrar, srv MediaAnalyzerServer) {
	// If the following call panics, it indicates UnimplementedMediaAnalyzerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaAnalyzer_ServiceDesc, srv)
}

func _MediaAnalyzer_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaAnalyzerServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaAnalyzer_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaAnalyzerServer).Analyze(ctx, req.(*AnalyzeMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaAnalyzer_ServiceDesc is the grpc.ServiceDesc for MediaAnalyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaAnalyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.MediaAnalyzer",
	HandlerType: (*MediaAnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _MediaAnalyzer_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/media_analyzer.proto",
}
