// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/media_analyzer.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeMediaRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MediaPath       string                 `protobuf:"bytes,1,opt,name=media_path,json=mediaPath,proto3" json:"media_path,omitempty"`
	FileHash        string                 `protobuf:"bytes,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeMediaRequest) Reset() {
	*x = AnalyzeMediaRequest{}
	mi := &file_silo_plugin_v1_media_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeMediaRequest) ProtoMessage() {}

func (x *AnalyzeMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_media_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeMediaRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeMediaRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_media_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeMediaRequest) GetMediaPath() string {
	if x != nil {
		return x.MediaPath
	}
	return ""
}

func (x *AnalyzeMediaRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *AnalyzeMediaRequest) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *AnalyzeMediaRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MarkerRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartSeconds  float64                `protobuf:"fixed64,1,opt,name=start_seconds,json=startSeconds,proto3" json:"start_seconds,omitempty"`
	EndSeconds    float64                `protobuf:"fixed64,2,opt,name=end_seconds,json=endSeconds,proto3" json:"end_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkerRange) Reset() {
	*x = MarkerRange{}
	mi := &file_silo_plugin_v1_media_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkerRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerRange) ProtoMessage() {}

func (x *MarkerRange) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_media_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerRange.ProtoReflect.Descriptor instead.
func (*MarkerRange) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_media_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *MarkerRange) GetStartSeconds() float64 {
	if x != nil {
		return x.StartSeconds
	}
	return 0
}

func (x *MarkerRange) GetEndSeconds() float64 {
	if x != nil {
		return x.EndSeconds
	}
	return 0
}

type AnalyzeMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intro         *MarkerRange           `protobuf:"bytes,1,opt,name=intro,proto3" json:"intro,omitempty"`
	Credits       *MarkerRange           `protobuf:"bytes,2,opt,name=credits,proto3" json:"credits,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeMediaResponse) Reset() {
	*x = AnalyzeMediaResponse{}
	mi := &file_silo_plugin_v1_media_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeMediaResponse) ProtoMessage() {}

func (x *AnalyzeMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_media_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeMediaResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeMediaResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_media_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeMediaResponse) GetIntro() *MarkerRange {
	if x != nil {
		return x.Intro
	}
	return nil
}

func (x *AnalyzeMediaResponse) GetCredits() *MarkerRange {
	if x != nil {
		return x.Credits
	}
	return nil
}

func (x *AnalyzeMediaResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalyzeMediaResponse) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_silo_plugin_v1_media_analyzer_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_media_analyzer_proto_rawDesc = "" +
	"\n" +
	"#silo/plugin/v1/media_analyzer.proto\x12\x0esilo.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xb1\x01\n" +
	"\x13AnalyzeMediaRequest\x12\x1d\n" +
	"\n" +
	"media_path\x18\x01 \x01(\tR\tmediaPath\x12\x1b\n" +
	"\tfile_hash\x18\x02 \x01(\tR\bfileHash\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x01R\x0fdurationSeconds\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"S\n" +
	"\vMarkerRange\x12#\n" +
	"\rstart_seconds\x18\x01 \x01(\x01R\fstartSeconds\x12\x1f\n" +
	"\vend_seconds\x18\x02 \x01(\x01R\n" +
	"endSeconds\"\xd5\x01\n" +
	"\x14AnalyzeMediaResponse\x121\n" +
	"\x05intro\x18\x01 \x01(\v2\x1b.silo.plugin.v1.MarkerRangeR\x05intro\x125\n" +
	"\acredits\x18\x02 \x01(\v2\x1b.silo.plugin.v1.MarkerRangeR\acredits\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata2e\n" +
	"\rMediaAnalyzer\x12T\n" +
	"\aAnalyze\x12#.silo.plugin.v1.AnalyzeMediaRequest\x1a$.silo.plugin.v1.AnalyzeMediaResponseBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_media_analyzer_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_media_analyzer_proto_rawDescData []byte
)

func file_silo_plugin_v1_media_analyzer_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_media_analyzer_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_media_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_media_analyzer_proto_rawDesc), len(file_silo_plugin_v1_media_analyzer_proto_rawDesc)))
	})
	return file_silo_plugin_v1_media_analyzer_proto_rawDescData
}

var file_silo_plugin_v1_media_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_silo_plugin_v1_media_analyzer_proto_goTypes = []any{
	(*AnalyzeMediaRequest)(nil),  // 0: silo.plugin.v1.AnalyzeMediaRequest
	(*MarkerRange)(nil),          // 1: silo.plugin.v1.MarkerRange
	(*AnalyzeMediaResponse)(nil), // 2: silo.plugin.v1.AnalyzeMediaResponse
	(*structpb.Struct)(nil),      // 3: google.protobuf.Struct
}
var file_silo_plugin_v1_media_analyzer_proto_depIdxs = []int32{
	3, // 0: silo.plugin.v1.AnalyzeMediaRequest.metadata:type_name -> google.protobuf.Struct
	1, // 1: silo.plugin.v1.AnalyzeMediaResponse.intro:type_name -> silo.plugin.v1.MarkerRange
	1, // 2: silo.plugin.v1.AnalyzeMediaResponse.credits:type_name -> silo.plugin.v1.MarkerRange
	3, // 3: silo.plugin.v1.AnalyzeMediaResponse.metadata:type_name -> google.protobuf.Struct
	0, // 4: silo.plugin.v1.MediaAnalyzer.Analyze:input_type -> silo.plugin.v1.AnalyzeMediaRequest
	2, // 5: silo.plugin.v1.MediaAnalyzer.Analyze:output_type -> silo.plugin.v1.AnalyzeMediaResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_media_analyzer_proto_init() }
func file_silo_plugin_v1_media_analyzer_proto_init() {
	if File_silo_plugin_v1_media_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_media_analyzer_proto_rawDesc), len(file_silo_plugin_v1_media_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_media_analyzer_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_media_analyzer_proto_depIdxs,
		MessageInfos:      file_silo_plugin_v1_media_analyzer_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_media_analyzer_proto = out.File
	file_silo_plugin_v1_media_analyzer_proto_goTypes = nil
	file_silo_plugin_v1_media_analyzer_proto_depIdxs = nil
}
