// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/metadata_provider.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataProvider_Search_FullMethodName           = "/silo.plugin.v1.MetadataProvider/Search"
	MetadataProvider_GetMetadata_FullMethodName      = "/silo.plugin.v1.MetadataProvider/GetMetadata"
	MetadataProvider_GetPersonDetail_FullMethodName  = "/silo.plugin.v1.MetadataProvider/GetPersonDetail"
	MetadataProvider_GetSeasons_FullMethodName       = "/silo.plugin.v1.MetadataProvider/GetSeasons"
	MetadataProvider_GetEpisodes_FullMethodName      = "/silo.plugin.v1.MetadataProvider/GetEpisodes"
	MetadataProvider_GetImages_FullMethodName        = "/silo.plugin.v1.MetadataProvider/GetImages"
	MetadataProvider_ResolveImageURL_FullMethodName  = "/silo.plugin.v1.MetadataProvider/ResolveImageURL"
	MetadataProvider_ResolveImageURLs_FullMethodName = "/silo.plugin.v1.MetadataProvider/ResolveImageURLs"
)

// MetadataProviderClient is the client API for MetadataProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetadataProviderClient interface {
	Search(ctx context.Context, in *SearchMetadataRequest, opts ...grpc.CallOption) (*SearchMetadataResponse, error)
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
	GetPersonDetail(ctx context.Context, in *GetPersonDetailRequest, opts ...grpc.CallOption) (*GetPersonDetailResponse, error)
	GetSeasons(ctx context.Context, in *GetSeasonsRequest, opts ...grpc.CallOption) (*GetSeasonsResponse, error)
	GetEpisodes(ctx context.Context, in *GetEpisodesRequest, opts ...grpc.CallOption) (*GetEpisodesResponse, error)
	GetImages(ctx context.Context, in *GetImagesRequest, opts ...grpc.CallOption) (*GetImagesResponse, error)
	ResolveImageURL(ctx context.Context, in *ResolveImageURLRequest, opts ...grpc.CallOption) (*ResolveImageURLResponse, error)
	ResolveImageURLs(ctx context.Context, in *ResolveImageURLsRequest, opts ...grpc.CallOption) (*ResolveImageURLsResponse, error)
}

type metadataProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataProviderClient(cc grpc.ClientConnInterface) MetadataProviderClient {
	return &metadataProviderClient{cc}
}

func (c *metadataProviderClient) Search(ctx context.Context, in *SearchMetadataRequest, opts ...grpc.CallOption) (*SearchMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchMetadataResponse)
	err := c.cc.Invoke(ctx, MetadataProvider_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataProviderClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, MetadataProvider_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataProviderClient) GetPersonDetail(ctx context.Context, in *GetPersonDetailRequest, opts ...grpc.CallOption) (*GetPersonDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPersonDetailResponse)
	err := c.cc.Invoke(ctx, MetadataProvider_GetPersonDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataProviderClient) GetSeasons(ctx context.Context, in *GetSeasonsRequest, opts ...grpc.CallOption) (*GetSeasonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeasonsResponse)
	err := c.cc.Invoke(ctx, MetadataProvider_GetSeasons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataProviderClient) GetEpisodes(ctx context.Context, in *GetEpisodesRequest, opts ...grpc.CallOption) (*GetEpisodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEpisodesResponse)
	err := c.cc.Invoke(ctx, MetadataProvider_GetEpisodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataProviderClient) GetImages(ctx context.Context, in *GetImagesRequest, opts ...grpc.CallOption) (*GetImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImagesResponse)
	err := c.cc.Invoke(ctx, MetadataProvider_GetImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataProviderClient) ResolveImageURL(ctx context.Context, in *ResolveImageURLRequest, opts ...grpc.CallOption) (*ResolveImageURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveImageURLResponse)
	err := c.cc.Invoke(ctx, MetadataProvider_ResolveImageURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataProviderClient) ResolveImageURLs(ctx context.Context, in *ResolveImageURLsRequest, opts ...grpc.CallOption) (*ResolveImageURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveImageURLsResponse)
	err := c.cc.Invoke(ctx, MetadataProvider_ResolveImageURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataProviderServer is the server API for MetadataProvider service.
// All implementations should embed UnimplementedMetadataProviderServer
// for forward compatibility.
type MetadataProviderServer interface {
	Search(context.Context, *SearchMetadataRequest) (*SearchMetadataResponse, error)
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	GetPersonDetail(context.Context, *GetPersonDetailRequest) (*GetPersonDetailResponse, error)
	GetSeasons(context.Context, *GetSeasonsRequest) (*GetSeasonsResponse, error)
	GetEpisodes(context.Context, *GetEpisodesRequest) (*GetEpisodesResponse, error)
	GetImages(context.Context, *GetImagesRequest) (*GetImagesResponse, error)
	ResolveImageURL(context.Context, *ResolveImageURLRequest) (*ResolveImageURLResponse, error)
	ResolveImageURLs(context.Context, *ResolveImageURLsRequest) (*ResolveImageURLsResponse, error)
}

// UnimplementedMetadataProviderServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataProviderServer struct{}

func (UnimplementedMetadataProviderServer) Search(context.Context, *SearchMetadataRequest) (*SearchMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMetadataProviderServer) GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedMetadataProviderServer) GetPersonDetail(context.Context, *GetPersonDetailRequest) (*GetPersonDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPersonDetail not implemented")
}
func (UnimplementedMetadataProviderServer) GetSeasons(context.Context, *GetSeasonsRequest) (*GetSeasonsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeasons not implemented")
}
func (UnimplementedMetadataProviderServer) GetEpisodes(context.Context, *GetEpisodesRequest) (*GetEpisodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEpisodes not implemented")
}
func (UnimplementedMetadataProviderServer) GetImages(context.Context, *GetImagesRequest) (*GetImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImages not implemented")
}
func (UnimplementedMetadataProviderServer) ResolveImageURL(context.Context, *ResolveImageURLRequest) (*ResolveImageURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveImageURL not implemented")
}
func (UnimplementedMetadataProviderServer) ResolveImageURLs(context.Context, *ResolveImageURLsRequest) (*ResolveImageURLsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveImageURLs not implemented")
}
func (UnimplementedMetadataProviderServer) testEmbeddedByValue() {}

// UnsafeMetadataProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataProviderServer will
// result in compilation errors.
type UnsafeMetadataProviderServer interface {
	mustEmbedUnimplementedMetadataProviderServer()
}

func RegisterMetadataProviderServer(s grpc.ServiceRegistrar, srv MetadataProviderServer) {
	// If the following call panics, it indicates UnimplementedMetadataProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataProvider_ServiceDesc, srv)
}

func _MetadataProvider_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataProviderServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataProvider_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataProviderServer).Search(ctx, req.(*SearchMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataProvider_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataProviderServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataProvider_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataProviderServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataProvider_GetPersonDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataProviderServer).GetPersonDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataProvider_GetPersonDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataProviderServer).GetPersonDetail(ctx, req.(*GetPersonDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataProvider_GetSeasons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeasonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataProviderServer).GetSeasons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataProvider_GetSeasons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataProviderServer).GetSeasons(ctx, req.(*GetSeasonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataProvider_GetEpisodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEpisodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataProviderServer).GetEpisodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataProvider_GetEpisodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataProviderServer).GetEpisodes(ctx, req.(*GetEpisodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataProvider_GetImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataProviderServer).GetImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataProvider_GetImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataProviderServer).GetImages(ctx, req.(*GetImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataProvider_ResolveImageURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveImageURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataProviderServer).ResolveImageURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataProvider_ResolveImageURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataProviderServer).ResolveImageURL(ctx, req.(*ResolveImageURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataProvider_ResolveImageURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveImageURLsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataProviderServer).ResolveImageURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataProvider_ResolveImageURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataProviderServer).ResolveImageURLs(ctx, req.(*ResolveImageURLsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataProvider_ServiceDesc is the grpc.ServiceDesc for MetadataProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.MetadataProvider",
	HandlerType: (*MetadataProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _MetadataProvider_Search_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _MetadataProvider_GetMetadata_Handler,
		},
		{
			MethodName: "GetPersonDetail",
			Handler:    _MetadataProvider_GetPersonDetail_Handler,
		},
		{
			MethodName: "GetSeasons",
			Handler:    _MetadataProvider_GetSeasons_Handler,
		},
		{
			MethodName: "GetEpisodes",
			Handler:    _MetadataProvider_GetEpisodes_Handler,
		},
		{
			MethodName: "GetImages",
			Handler:    _MetadataProvider_GetImages_Handler,
		},
		{
			MethodName: "ResolveImageURL",
			Handler:    _MetadataProvider_ResolveImageURL_Handler,
		},
		{
			MethodName: "ResolveImageURLs",
			Handler:    _MetadataProvider_ResolveImageURLs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/metadata_provider.proto",
}
