// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/request_router.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequestRouter_Fulfill_FullMethodName           = "/silo.plugin.v1.RequestRouter/Fulfill"
	RequestRouter_CheckStatus_FullMethodName       = "/silo.plugin.v1.RequestRouter/CheckStatus"
	RequestRouter_ListConfigOptions_FullMethodName = "/silo.plugin.v1.RequestRouter/ListConfigOptions"
	RequestRouter_TestConnection_FullMethodName    = "/silo.plugin.v1.RequestRouter/TestConnection"
	RequestRouter_Validate_FullMethodName          = "/silo.plugin.v1.RequestRouter/Validate"
)

// RequestRouterClient is the client API for RequestRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RequestRouter lets the host delegate whole-request fulfillment to a backend
// plugin (e.g. multi-instance Sonarr/Radarr, Seerr). The host owns the request
// lifecycle, quota/policy, the allowed-quality governance, and the target
// records; the plugin owns instance routing, submission, and status semantics.
// Connections are passed per call; the plugin stores no credentials.
type RequestRouterClient interface {
	Fulfill(ctx context.Context, in *FulfillRequest, opts ...grpc.CallOption) (*FulfillResponse, error)
	CheckStatus(ctx context.Context, in *CheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusResponse, error)
	ListConfigOptions(ctx context.Context, in *ListConfigOptionsRequest, opts ...grpc.CallOption) (*ListConfigOptionsResponse, error)
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type requestRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestRouterClient(cc grpc.ClientConnInterface) RequestRouterClient {
	return &requestRouterClient{cc}
}

func (c *requestRouterClient) Fulfill(ctx context.Context, in *FulfillRequest, opts ...grpc.CallOption) (*FulfillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FulfillResponse)
	err := c.cc.Invoke(ctx, RequestRouter_Fulfill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestRouterClient) CheckStatus(ctx context.Context, in *CheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckStatusResponse)
	err := c.cc.Invoke(ctx, RequestRouter_CheckStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestRouterClient) ListConfigOptions(ctx context.Context, in *ListConfigOptionsRequest, opts ...grpc.CallOption) (*ListConfigOptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigOptionsResponse)
	err := c.cc.Invoke(ctx, RequestRouter_ListConfigOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestRouterClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectionResponse)
	err := c.cc.Invoke(ctx, RequestRouter_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestRouterClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, RequestRouter_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestRouterServer is the server API for RequestRouter service.
// All implementations should embed UnimplementedRequestRouterServer
// for forward compatibility.
//
// RequestRouter lets the host delegate whole-request fulfillment to a backend
// plugin (e.g. multi-instance Sonarr/Radarr, Seerr). The host owns the request
// lifecycle, quota/policy, the allowed-quality governance, and the target
// records; the plugin owns instance routing, submission, and status semantics.
// Connections are passed per call; the plugin stores no credentials.
type RequestRouterServer interface {
	Fulfill(context.Context, *FulfillRequest) (*FulfillResponse, error)
	CheckStatus(context.Context, *CheckStatusRequest) (*CheckStatusResponse, error)
	ListConfigOptions(context.Context, *ListConfigOptionsRequest) (*ListConfigOptionsResponse, error)
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
}

// UnimplementedRequestRouterServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequestRouterServer struct{}

func (UnimplementedRequestRouterServer) Fulfill(context.Context, *FulfillRequest) (*FulfillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fulfill not implemented")
}
func (UnimplementedRequestRouterServer) CheckStatus(context.Context, *CheckStatusRequest) (*CheckStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckStatus not implemented")
}
func (UnimplementedRequestRouterServer) ListConfigOptions(context.Context, *ListConfigOptionsRequest) (*ListConfigOptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConfigOptions not implemented")
}
func (UnimplementedRequestRouterServer) TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedRequestRouterServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedRequestRouterServer) testEmbeddedByValue() {}

// UnsafeRequestRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequestRouterServer will
// result in compilation errors.
type UnsafeRequestRouterServer interface {
	mustEmbedUnimplementedRequestRouterServer()
}

func RegisterRequestRouterServer(s grpc.ServiceRegistrar, srv RequestRouterServer) {
	// If the following call panics, it indicates UnimplementedRequestRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequestRouter_ServiceDesc, srv)
}

func _RequestRouter_Fulfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FulfillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestRouterServer).Fulfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestRouter_Fulfill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestRouterServer).Fulfill(ctx, req.(*FulfillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestRouter_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestRouterServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestRouter_CheckStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestRouterServer).CheckStatus(ctx, req.(*CheckStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestRouter_ListConfigOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestRouterServer).ListConfigOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestRouter_ListConfigOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestRouterServer).ListConfigOptions(ctx, req.(*ListConfigOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestRouter_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestRouterServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestRouter_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestRouterServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestRouter_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestRouterServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestRouter_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestRouterServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequestRouter_ServiceDesc is the grpc.ServiceDesc for RequestRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequestRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.RequestRouter",
	HandlerType: (*RequestRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fulfill",
			Handler:    _RequestRouter_Fulfill_Handler,
		},
		{
			MethodName: "CheckStatus",
			Handler:    _RequestRouter_CheckStatus_Handler,
		},
		{
			MethodName: "ListConfigOptions",
			Handler:    _RequestRouter_ListConfigOptions_Handler,
		},
		{
			MethodName: "TestConnection",
			Handler:    _RequestRouter_TestConnection_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _RequestRouter_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/request_router.proto",
}
