// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/scan_source.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScanSource_PollChanges_FullMethodName = "/silo.plugin.v1.ScanSource/PollChanges"
)

// ScanSourceClient is the client API for ScanSource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScanSource lets the host pull changed filesystem paths from a provider
// (e.g. Sonarr/Radarr, inotify, Ceph). Pull only: the host owns the timer,
// marker storage, path rewrites, and scan enqueueing; the plugin never
// initiates.
type ScanSourceClient interface {
	PollChanges(ctx context.Context, in *PollChangesRequest, opts ...grpc.CallOption) (*PollChangesResponse, error)
}

type scanSourceClient struct {
	cc grpc.ClientConnInterface
}

func NewScanSourceClient(cc grpc.ClientConnInterface) ScanSourceClient {
	return &scanSourceClient{cc}
}

func (c *scanSourceClient) PollChanges(ctx context.Context, in *PollChangesRequest, opts ...grpc.CallOption) (*PollChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollChangesResponse)
	err := c.cc.Invoke(ctx, ScanSource_PollChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScanSourceServer is the server API for ScanSource service.
// All implementations should embed UnimplementedScanSourceServer
// for forward compatibility.
//
// ScanSource lets the host pull changed filesystem paths from a provider
// (e.g. Sonarr/Radarr, inotify, Ceph). Pull only: the host owns the timer,
// marker storage, path rewrites, and scan enqueueing; the plugin never
// initiates.
type ScanSourceServer interface {
	PollChanges(context.Context, *PollChangesRequest) (*PollChangesResponse, error)
}

// UnimplementedScanSourceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScanSourceServer struct{}

func (UnimplementedScanSourceServer) PollChanges(context.Context, *PollChangesRequest) (*PollChangesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollChanges not implemented")
}
func (UnimplementedScanSourceServer) testEmbeddedByValue() {}

// UnsafeScanSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScanSourceServer will
// result in compilation errors.
type UnsafeScanSourceServer interface {
	mustEmbedUnimplementedScanSourceServer()
}

func RegisterScanSourceServer(s grpc.ServiceRegistrar, srv ScanSourceServer) {
	// If the following call panics, it indicates UnimplementedScanSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScanSource_ServiceDesc, srv)
}

func _ScanSource_PollChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanSourceServer).PollChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScanSource_PollChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanSourceServer).PollChanges(ctx, req.(*PollChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScanSource_ServiceDesc is the grpc.ServiceDesc for ScanSource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScanSource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.ScanSource",
	HandlerType: (*ScanSourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PollChanges",
			Handler:    _ScanSource_PollChanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/scan_source.proto",
}
