// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/scheduled_task.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScheduledTask_Run_FullMethodName = "/silo.plugin.v1.ScheduledTask/Run"
)

// ScheduledTaskClient is the client API for ScheduledTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScheduledTaskClient interface {
	Run(ctx context.Context, in *RunScheduledTaskRequest, opts ...grpc.CallOption) (*RunScheduledTaskResponse, error)
}

type scheduledTaskClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduledTaskClient(cc grpc.ClientConnInterface) ScheduledTaskClient {
	return &scheduledTaskClient{cc}
}

func (c *scheduledTaskClient) Run(ctx context.Context, in *RunScheduledTaskRequest, opts ...grpc.CallOption) (*RunScheduledTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunScheduledTaskResponse)
	err := c.cc.Invoke(ctx, ScheduledTask_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduledTaskServer is the server API for ScheduledTask service.
// All implementations should embed UnimplementedScheduledTaskServer
// for forward compatibility.
type ScheduledTaskServer interface {
	Run(context.Context, *RunScheduledTaskRequest) (*RunScheduledTaskResponse, error)
}

// UnimplementedScheduledTaskServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScheduledTaskServer struct{}

func (UnimplementedScheduledTaskServer) Run(context.Context, *RunScheduledTaskRequest) (*RunScheduledTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedScheduledTaskServer) testEmbeddedByValue() {}

// UnsafeScheduledTaskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduledTaskServer will
// result in compilation errors.
type UnsafeScheduledTaskServer interface {
	mustEmbedUnimplementedScheduledTaskServer()
}

func RegisterScheduledTaskServer(s grpc.ServiceRegistrar, srv ScheduledTaskServer) {
	// If the following call panics, it indicates UnimplementedScheduledTaskServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScheduledTask_ServiceDesc, srv)
}

func _ScheduledTask_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunScheduledTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduledTaskServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScheduledTask_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduledTaskServer).Run(ctx, req.(*RunScheduledTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduledTask_ServiceDesc is the grpc.ServiceDesc for ScheduledTask service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduledTask_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.ScheduledTask",
	HandlerType: (*ScheduledTaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _ScheduledTask_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/scheduled_task.proto",
}
